var subject = require('./subject.js')
var mock = require('mock-fs');
subject.inc(0,undefined);
subject.inc('-1','1');
subject.inc('1','undefined');
subject.inc('1','1');
subject.inc('1','0');
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
subject.normalize('212-323-221');
subject.normalize('599-911-9460');
subject.format('','',false);
subject.format('144-162-1121','###.###.#### x#####',{normalize:true});
subject.format('144-162-1121','###.###.#### x#####',{normalize:false});
subject.format('144-162-1121','###.###.#### x#####',false);
subject.blackListNumber('212-323-221');
subject.blackListNumber('180-204-9873');
